"""Alias rewrite MVP helpers for UTAU oto.ini pitch annotation."""

from .aliases import AliasRewriteConfig, build_alias_change, resolve_duplicate_aliases
from .apply import ApplyOptions, ApplyResult, apply_changes_direct
from .backup import BackupResult, backup_directory, backup_file
from .changes import (
    ChangeRow,
    CsvApplyResult,
    apply_changes_csv_to_oto_file,
    apply_changes_to_oto_file,
    changes_from_preview_rows,
    invert_changes,
    merge_changes,
    read_changes_csv,
    write_changes_csv,
)
from .filename import FilenameRewriteConfig, build_filename_rewrite_changes
from .wav_names import hidden_wav_name
from .files import FileRenamePlan, FileRenameResult, apply_file_rename_plan, build_file_rename_plan
from .frq import FrqParseError, FrqRecord, parse_frq, parse_frq_directory, parse_pmk, parse_pmk_directory
from .information import PitchDistributionBin, VoiceInformation, build_voice_information
from .keys import (
    CallKey,
    KeyWarning,
    KeyWarningConfig,
    apply_changes_to_entries,
    call_keys_for_entry,
    call_key_candidates_for_entry,
    detect_call_key_collisions,
    detect_resolution_warnings,
    pronunciation_mora,
    resolve_call_key,
    warning_summary_by_line,
    wav_key,
)
from .mrq import MrqParseError, MrqRecord, parse_mrq, valid_f0_values
from .notes import NoteMappingConfig, freq_to_note
from .options import SortDirection, WarningSeverity, WavEditMode
from .oto import OtoEntry, OtoLine, parse_oto_file, write_oto_copy
from .pitch import build_frequency_index, build_mrq_index, estimate_pitch_for_entry, load_frequency_records
from .rewrite import (
    ExcludeConfig,
    PreviewOptions,
    ReplacementRule,
    RewritePreviewRow,
    SortKeyOrder,
    export_rewrite_preview_csv,
    merge_change_csv_files,
    preview_changes,
    preview_rewrite,
    rewrite_oto_file,
    rewrite_oto_file_from_csv,
    validate_preview_changes,
)
from .ust import UstDocument, parse_ust_file, replace_lyrics, write_ust_document
from .ust_sync import (
    UstSyncPreview,
    apply_ust_sync_for_file,
    build_ust_alias_map,
    preview_ust_sync_for_file,
    preview_ust_sync_for_folder,
)
from .ust_usage import (
    UnresolvedLyric,
    UstLineUsage,
    UstLyricOccurrence,
    UstUsageDocument,
    UstUsageSummary,
    collect_ust_usage,
    scan_ust_usage_documents,
)
from .voice_scan import UstScanResult, scan_ust_files, voice_dir_matches
from .warnings import WarningMessage, has_blocking_warnings, warnings_from_changes

__all__ = [
    "AliasRewriteConfig",
    "ApplyOptions",
    "ApplyResult",
    "BackupResult",
    "CallKey",
    "ChangeRow",
    "CsvApplyResult",
    "FileRenamePlan",
    "FileRenameResult",
    "FilenameRewriteConfig",
    "FrqParseError",
    "FrqRecord",
    "ExcludeConfig",
    "KeyWarning",
    "KeyWarningConfig",
    "MrqParseError",
    "MrqRecord",
    "NoteMappingConfig",
    "OtoEntry",
    "OtoLine",
    "PitchDistributionBin",
    "RewritePreviewRow",
    "PreviewOptions",
    "ReplacementRule",
    "UstDocument",
    "UstScanResult",
    "UstSyncPreview",
    "UstUsageDocument",
    "UstLineUsage",
    "UstLyricOccurrence",
    "UstUsageSummary",
    "VoiceInformation",
    "SortDirection",
    "SortKeyOrder",
    "WarningMessage",
    "WarningSeverity",
    "WavEditMode",
    "apply_changes_csv_to_oto_file",
    "apply_changes_to_oto_file",
    "apply_changes_direct",
    "apply_changes_to_entries",
    "apply_file_rename_plan",
    "apply_ust_sync_for_file",
    "backup_file",
    "backup_directory",
    "build_alias_change",
    "build_file_rename_plan",
    "build_frequency_index",
    "build_filename_rewrite_changes",
    "build_mrq_index",
    "build_ust_alias_map",
    "build_voice_information",
    "call_keys_for_entry",
    "call_key_candidates_for_entry",
    "changes_from_preview_rows",
    "detect_call_key_collisions",
    "detect_resolution_warnings",
    "estimate_pitch_for_entry",
    "export_rewrite_preview_csv",
    "freq_to_note",
    "hidden_wav_name",
    "has_blocking_warnings",
    "invert_changes",
    "load_frequency_records",
    "merge_change_csv_files",
    "merge_changes",
    "parse_mrq",
    "parse_frq",
    "parse_frq_directory",
    "parse_pmk",
    "parse_pmk_directory",
    "parse_oto_file",
    "parse_ust_file",
    "preview_rewrite",
    "preview_changes",
    "validate_preview_changes",
    "preview_ust_sync_for_file",
    "preview_ust_sync_for_folder",
    "pronunciation_mora",
    "read_changes_csv",
    "replace_lyrics",
    "resolve_duplicate_aliases",
    "resolve_call_key",
    "rewrite_oto_file",
    "rewrite_oto_file_from_csv",
    "collect_ust_usage",
    "scan_ust_files",
    "scan_ust_usage_documents",
    "UnresolvedLyric",
    "valid_f0_values",
    "voice_dir_matches",
    "warning_summary_by_line",
    "warnings_from_changes",
    "wav_key",
    "write_changes_csv",
    "write_oto_copy",
    "write_ust_document",
]
